#--------------------------------------------------------------------------
# Oh My Zsh
#--------------------------------------------------------------------------

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(
    artisan
    composer
    git
    zsh-autosuggestions
    poetry
)

source $ZSH/oh-my-zsh.sh

#--------------------------------------------------------------------------
# Configuration
#--------------------------------------------------------------------------

path=(
    $HOME/.local/bin
    $HOME/.config/composer/vendor/bin
    $path
)

export EDITOR=vim
export GIT_EDITOR=vim

#--------------------------------------------------------------------------
# Aliases
#--------------------------------------------------------------------------

alias vim="nvim"
alias cat="bat"

# Git
alias g="git"
alias gs="git s"
alias wip="git add . && git commit -m 'wip'"

# Laravel
alias a="artisan"
alias migrate="artisan migrate"
alias tinker="artisan tinker"
alias serve="artisan serve"
alias pest="clear && ./vendor/bin/pest"
alias pint="./vendor/bin/pint"

#--------------------------------------------------------------------------
# VSCode
#--------------------------------------------------------------------------

[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"

